### ISSUE TITLE
HttpApplication.EndProcessRequest vs. execution of results

### ISSUE THREAD

**Issue by jorupp** [devtrends/Unity.Mvc5#1]
I'm seeing an issue in my application where sometimes result objects returned from my controller are executed _after_ the container is disposed in the HttpApplication.EndProcessRequest event handler.

Looking at http://i2.asp.net/media/4773381/lifecycle-of-an-aspnet-mvc-5-application.pdf?cdn_id=2015-04-01-001, it seems that (in MVC 5 at least) with async processing, results are executed during HttpApplication.EndProcessRequest, leading to the possibility of a race condition between the container cleanup and result execution.

I don't have any async or otherwise Task-returning controller actions, but I occasionally will get error messages during rendering of views about a on of my services being disposed when it tries to use it.

Is HttpApplication.EndProcessRequest still the right place for these hooks in MVC 5?  Here's a comparison of the call stacks where one of my services is getting `.Dispose()` called by the container, and a trace of the error:

```
...
   at Unity.Mvc3.UnityDependencyResolver.DisposeOfChildContainer()
   at Unity.Mvc3.RequestLifetimeHttpModule.<Init>b__0(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

```
...
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +294
...
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +62
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +47
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9651188
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

**Comment by jorupp** [comment]
Just thought to look at my references... This project wasn't actually upgraded to MVC 5 like I thought - it's a MVC 4 app and not even using this version of the library :(
